### ISSUE TITLE
License

### ISSUE THREAD

**Issue by futuretim** [fieldkit/cloud#78]
Can you please add a license to this repo? I would potentially like to base an open source project on some of the code here and need to know what it will take to comply. Thanks!

**Comment by jlewallen** [comment]
Hey there! Absolutely! I'll update the repository very soon. In the meantime you can refer to the licenses here: https://www.fieldkit.org/licenses/

**Comment by jlewallen** [comment]
Done!

https://github.com/fieldkit/cloud/commit/4393b7e040c7e641904e95fc03678cfe6e80496a

**Comment by futuretim** [comment]
Awesome, thank-you @jlewallen !
